name: Архивировать ссылки

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # At 03:00 UTC every day

permissions:
  contents: write

jobs:
  archive-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          uv sync --all-groups --link-mode=copy;
          
      - name: Run archive script
        env:
          API_KEY: ${{ secrets.READWISE_API_KEY }}
        run: |
          uv run ./app/main.py --api-key "$API_KEY"
          
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Отчёты от ${timestamp}" || exit 0
          git pull --rebase
          git push